### ISSUE TITLE
destination file's permission can't be edited

### ISSUE THREAD

**Issue by sebinjohn** [maestrodev/puppet-wget#37]
I am facing an issue to give permission to the destination file when the cache dir is set, because the the resource is already defined in the wget::fetch module. So the workaround is to set the destination to a temporary location  and create a new resource by sourcing it to from the temporary location.

    file { $destination:
      ensure  => file,
      source  => "${cache_dir}/${cache}",
      owner   => $execuser,
      require => Exec["wget-${name}"],
    }

this is the code from the wget::fetch module.

**Comment by gauthier-delacroix** [comment]
+1

**Comment by mcallaway** [comment]
+1

**Comment by carlossg** [comment]
can you suggest a PR ?

**Comment by mcallaway** [comment]
Working on a PR now.

**Comment by carlossg** [comment]
Fixed in #44

**Comment by c33s** [comment]
vote for reopen. 

if i want to prevent the access from other user (`mode 0400`), this don't really fix the problem, it just moves it. with this fix i have to to ensure, that the cache location is in a directory where no other user can access the file. so `/tmp` or `/var/tmp` or `/var/cache` won't work.

the solution from https://unix.stackexchange.com/questions/118670/changing-default-permissions-for-wget is to call `umask` before `wget`, maybe this is also here a solution.

my workaround was to create a directory with the right permission, which i use as cache directory but sadly this workaround don't work for me, because i only want to download the file once and not redownload if the remote file chances. but there is no `creates` parameter which i can use. see #26
